/*
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 
*/

package kiyut.sketsa.modules.animation.windows;

import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.Collection;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeListener;
import kiyut.sketsa.cookies.SVGEditorCookie;
import org.openide.awt.UndoRedo;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays {@link AnimationEditor}
 * 
 * @author Tonny Kohar
 * 
 */
public final class AnimationTopComponent extends TopComponent {

    private static AnimationTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "AnimationTopComponent";
    
    private Lookup.Result result = null;
    private LookupListener editorCookieLookupListener = null;
    private UndoRedo undoRedo;
    private SVGEditorCookie editorCookie;
    private UndoRedo trackedDocumentUndoRedo;
    private ChangeListener trackedDocumentUndoRedoListener;
    
    private AnimationEditor animationEditor;

    private AnimationTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(AnimationTopComponent.class, "CTL_AnimationTopComponent"));
        setToolTipText(NbBundle.getMessage(AnimationTopComponent.class, "HINT_AnimationTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
        
        initCustomComponents();
        
        editorCookieLookupListener = new LookupListener() {
            @Override
            public void resultChanged(LookupEvent lookupEvent) {
                editorCookieLookupListenerResultChanged(lookupEvent);
            }
        };
        
        
        result = Utilities.actionsGlobalContext().lookupResult(SVGEditorCookie.class);
        result.addLookupListener(editorCookieLookupListener);

        // NetBeans does not fire a LookupEvent simply because a listener was attached.
        // If an SVG editor was already active when the Animation window opened, the
        // legacy 0.4 code therefore never connected the AnimationEditor to its canvas.
        // Synchronize once immediately with the current global context.
        refreshEditorCookieFromLookup();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized AnimationTopComponent getDefault() {
        if (instance == null) {
            instance = new AnimationTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the AnimationTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized AnimationTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(AnimationTopComponent.class.getName()).warning("Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof AnimationTopComponent) {
            return (AnimationTopComponent) win;
        }
        Logger.getLogger(AnimationTopComponent.class.getName()).warning("There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
    // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
    // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {
        private static final long serialVersionUID = 1L;
        public Object readResolve() {
            return AnimationTopComponent.getDefault();
        }
    }
    
    @Override
    public UndoRedo getUndoRedo() {
        refreshEditorCookieFromLookup();
        if (undoRedo == null) {
            return super.getUndoRedo();
        }
        return undoRedo;
    }

    @Override
    protected void componentActivated() {
        super.componentActivated();
        refreshEditorCookieFromLookup();
    }
    
    private void initCustomComponents() {
        animationEditor = new AnimationEditor();
        
        this.add(BorderLayout.CENTER,animationEditor);
    }
    
    private void editorCookieLookupListenerResultChanged(LookupEvent lookupEvent) {
        refreshEditorCookieFromLookup();
    }

    private void refreshEditorCookieFromLookup() {
        Collection c = result.allInstances();
        if (!c.isEmpty()) {
            SVGEditorCookie activeEditorCookie = (SVGEditorCookie)c.iterator().next();
            if (activeEditorCookie != editorCookie) {
                detachDocumentUndoTracking();
                editorCookie = activeEditorCookie;

                /*
                 * Animation authoring applies changes explicitly with the
                 * inspector's Apply button and creates real DOM undo
                 * transactions. Local text-field undo therefore interferes
                 * with the expected Ctrl+Z/Ctrl+Y workflow after Apply: the
                 * user wants document animation edits undone, not stale text
                 * edits inside the inspector controls.
                 */
                trackedDocumentUndoRedo =
                        new RefreshingUndoRedo(editorCookie.getUndoRedo());
                trackedDocumentUndoRedoListener = e ->
                        SwingUtilities.invokeLater(() -> {
                            if (animationEditor != null) {
                                animationEditor.refreshAfterUndoRedo();
                            }
                        });
                trackedDocumentUndoRedo.addChangeListener(
                        trackedDocumentUndoRedoListener);

                undoRedo = trackedDocumentUndoRedo;
                animationEditor.setVectorCanvas(editorCookie.getVectorCanvas());
            } else if (animationEditor != null && editorCookie != null) {
                animationEditor.setVectorCanvas(editorCookie.getVectorCanvas());
            }
        } else if (editorCookie != null && editorCookie.isOpened() == false) {
            detachDocumentUndoTracking();
            undoRedo = null;
            editorCookie = null;
            animationEditor.setVectorCanvas(null);
        }
    }

    private void detachDocumentUndoTracking() {
        if (trackedDocumentUndoRedo != null
                && trackedDocumentUndoRedoListener != null) {
            trackedDocumentUndoRedo.removeChangeListener(
                    trackedDocumentUndoRedoListener);
        }
        trackedDocumentUndoRedo = null;
        trackedDocumentUndoRedoListener = null;
    }
    /**
     * Sketsa's editor UndoRedo delegate does not notify NetBeans after undo()/redo().
     * Relay normal changes and explicitly fire after undo/redo so Redo becomes
     * enabled immediately while focus remains in this plugin TopComponent.
     */
    private static final class RefreshingUndoRedo implements UndoRedo {
        private final UndoRedo delegate;
        private final javax.swing.event.EventListenerList listeners = new javax.swing.event.EventListenerList();
        private final javax.swing.event.ChangeListener relay = e -> fireChange();

        RefreshingUndoRedo(UndoRedo delegate) {
            this.delegate = delegate;
            if (delegate != null) delegate.addChangeListener(relay);
        }

        @Override public boolean canUndo() { return delegate != null && delegate.canUndo(); }
        @Override public boolean canRedo() { return delegate != null && delegate.canRedo(); }
        @Override public void undo() throws javax.swing.undo.CannotUndoException {
            if (delegate == null) throw new javax.swing.undo.CannotUndoException();
            delegate.undo();
            fireChange();
        }
        @Override public void redo() throws javax.swing.undo.CannotRedoException {
            if (delegate == null) throw new javax.swing.undo.CannotRedoException();
            delegate.redo();
            fireChange();
        }
        @Override public String getUndoPresentationName() { return delegate == null ? "" : delegate.getUndoPresentationName(); }
        @Override public String getRedoPresentationName() { return delegate == null ? "" : delegate.getRedoPresentationName(); }
        @Override public void addChangeListener(javax.swing.event.ChangeListener l) { listeners.add(javax.swing.event.ChangeListener.class, l); }
        @Override public void removeChangeListener(javax.swing.event.ChangeListener l) { listeners.remove(javax.swing.event.ChangeListener.class, l); }
        private void fireChange() {
            javax.swing.event.ChangeEvent e = new javax.swing.event.ChangeEvent(this);
            for (javax.swing.event.ChangeListener l : listeners.getListeners(javax.swing.event.ChangeListener.class)) l.stateChanged(e);
        }
    }

}
