/*
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 
*/

package kiyut.sketsa.modules.animation.windows;

import java.awt.BorderLayout;
import java.io.Serializable;
import java.util.Collection;
import java.util.logging.Logger;
import kiyut.sketsa.cookies.SVGEditorCookie;
import org.openide.awt.UndoRedo;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays {@link AnimationEditor}
 * 
 * @author Tonny Kohar
 * 
 */
public final class AnimationTopComponent extends TopComponent {

    private static AnimationTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "AnimationTopComponent";
    
    private Lookup.Result result = null;
    private LookupListener editorCookieLookupListener = null;
    private UndoRedo undoRedo;
    private SVGEditorCookie editorCookie;
    
    private AnimationEditor animationEditor;

    private AnimationTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(AnimationTopComponent.class, "CTL_AnimationTopComponent"));
        setToolTipText(NbBundle.getMessage(AnimationTopComponent.class, "HINT_AnimationTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
        
        initCustomComponents();
        
        editorCookieLookupListener = new LookupListener() {
            @Override
            public void resultChanged(LookupEvent lookupEvent) {
                editorCookieLookupListenerResultChanged(lookupEvent);
            }
        };
        
        
        result = Utilities.actionsGlobalContext().lookupResult(SVGEditorCookie.class);
        result.addLookupListener(editorCookieLookupListener);

        // NetBeans does not fire a LookupEvent simply because a listener was attached.
        // If an SVG editor was already active when the Animation window opened, the
        // legacy 0.4 code therefore never connected the AnimationEditor to its canvas.
        // Synchronize once immediately with the current global context.
        refreshEditorCookieFromLookup();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized AnimationTopComponent getDefault() {
        if (instance == null) {
            instance = new AnimationTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the AnimationTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized AnimationTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(AnimationTopComponent.class.getName()).warning("Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof AnimationTopComponent) {
            return (AnimationTopComponent) win;
        }
        Logger.getLogger(AnimationTopComponent.class.getName()).warning("There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
    // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
    // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {
        private static final long serialVersionUID = 1L;
        public Object readResolve() {
            return AnimationTopComponent.getDefault();
        }
    }
    
    @Override
    public UndoRedo getUndoRedo() {
        if (undoRedo == null) {
            return super.getUndoRedo();
        }
        return undoRedo;
    }
    
    private void initCustomComponents() {
        animationEditor = new AnimationEditor();
        
        this.add(BorderLayout.CENTER,animationEditor);
    }
    
    private void editorCookieLookupListenerResultChanged(LookupEvent lookupEvent) {
        refreshEditorCookieFromLookup();
    }

    private void refreshEditorCookieFromLookup() {
        Collection c = result.allInstances();
        if (!c.isEmpty()) {
            SVGEditorCookie activeEditorCookie = (SVGEditorCookie)c.iterator().next();
            if (activeEditorCookie != editorCookie) {
                editorCookie = activeEditorCookie;
                undoRedo = editorCookie.getUndoRedo();
                animationEditor.setVectorCanvas(editorCookie.getVectorCanvas());
            }
        } else if (editorCookie != null && editorCookie.isOpened() == false) {
            undoRedo = null;
            editorCookie = null;
            animationEditor.setVectorCanvas(null);
        }
    }
}
